### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [stephanie-sswl/prj-rev-bwfs-dasmoto#6]
https://github.com/stephanie-sswl/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/stylesheet.css#L5

You're repeating this style in nearly every CSS rule. 

Put it into a single CSS rule with a more general selector instead:

```css
* {
  font-family: Helvetica;
}
```
